name: BreakerGift
main: fr.breakerland.breakergift.BreakerGift
api-version: 1.13
version: 2.0
description: Send a Christmas Gift !
website: https://github.com/Breakerland
authors: [AzodFR, LLIcocoman_Hrz]

commands:
  gift:
    usage: |
           §6=====================§c GIFT §6======================
           §7/<command> [player] : §eOffer a christmas gift to another player!
           §6=================================================
    description: send a gift !
    permission: gift.command.gift
    aliases: present
  giftadmin:
    usage: |
           §6===================§c GIFT ADMIN §6===================
           §7/<command> modify : §eLeft click on a chest to add or remove it from christmas chests
           §7/<command> giveall : §eOffer a christmas gift to all online players
           §6=================================================
    description: admin this gift
    permission: gift.command.giftadmin

permissions:
  gift.*:
    description: Wildcard permission.
    default: op
    children:
      gift.command.gift: true
      gift.command.giftadmin: true
  gift.command.gift:
    description: Use gift command.
    default: true
  gift.command.giftadmin:
    description: Use giftadmin command.
    default: op